---
title: "stl_lead_inequity"
format: html
editor: visual
---

## Read in and explore data

```{r}
library(tidyverse)
library(janitor)
```

```{r}

# reading in csv using the here fxn 
stl_lead <- read_csv(here::here("data", "stl_blood_lead.csv"))


# different ways to view data 
view(stl_lead)
skimr::skim(stl_lead)

dim(stl_lead)
names(stl_lead)

# clean up column names with janitor 
stl_lead <- stl_lead %>% janitor::clean_names()

```

```{r}

# adding a new column white/population x 100
         
stl_blood_prop <- stl_lead %>%
mutate(perc_white = (white / total_pop) * 100) %>%
  mutate(perc_black = (black / total_pop) * 100)



```

## Create a Scatterplot

```{r}

stl_lead_plot <- ggplot(data = stl_blood_prop,
       aes(x = pct_elevated, y = perc_white)) + 
  geom_point(colour = "green") + 
  theme_minimal() + 
  labs(title = "Percentage of Children in each census tract with Elevated Blood Lead Levels", 
       x = "Percent Elevated",
       y = "Proportion of White Children")

stl_lead_plot

  ggsave(here::here("figs", "stl_lead_plot.png"), height = 5,
         width = 6)
```
## The census tract with a higher percentage of white children generally had lower levels of lead blood percentage.

```{r}
stl_lead_histogram <- ggplot(data = stl_blood_prop,
       aes(x = pct_elevated)) + 
  geom_histogram(colour = "green") + 
  theme_minimal() + 
  labs(title = "Percentage of Children in each census tract with Elevated Blood Lead Levels", 
       x = "Percent Elevated",
       y = "Proportion of White Children")

stl_lead_histogram

ggsave(here::here("figs", "stl_lead_histogram.png"), height = 5,
         width = 6)
```
```

